framework:
  cache:
    pools:
      cache.my_redis:
        adapter: cache.adapter.redis
        provider: app.predis_provider

services:
  app.predis_provider:
    autowire: true
    class: \Predis\Client
    factory:
      ['Symfony\Component\Cache\Adapter\RedisAdapter', "createConnection"]
    arguments:
      - "redis://localhost:6379"
      - { retry_interval: 2, timeout: 10 }
