#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\BooksController::search
  methods: [GET]

book_create:
  path: /books/create
  controller: App\Controller\BooksController::create

search:
  path: /search/{id}
  controller: App\Controller\BooksController::search
  methods: [GET]
  defaults:
    id: null
